/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountItem: typeof import('./components/accounts/AccountItem.vue')['default']
    AccountLabelsField: typeof import('./components/accounts/fields/AccountLabelsField.vue')['default']
    AccountList: typeof import('./components/accounts/AccountList.vue')['default']
    AccountLoginField: typeof import('./components/accounts/fields/AccountLoginField.vue')['default']
    AccountPasswordField: typeof import('./components/accounts/fields/AccountPasswordField.vue')['default']
    AccountsForm: typeof import('./components/accounts/AccountsForm.vue')['default']
    AccountTypeField: typeof import('./components/accounts/fields/AccountTypeField.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
